primeiro_numero = int(input('Primeiro número: '))
segundo_numero = int(input('Segundo número: '))
soma = (primeiro_numero + segundo_numero)
# print('A soma dos números é ', soma)
print('A soma dos números {} e {} é {}!'.format(primeiro_numero, segundo_numero, soma))
